---
# tasks file for edjruntime
       - name: github login
         shell: echo ceae4f110341a90997dbbe55dc0d7375c8aabf32 | docker login https://docker.pkg.github.com -u sriedjx --password-stdin
       - name: edjcli binary
         shell: wget "https://docs.google.com/uc?export=download&id=13pWZgKU9hbR1nhKv-laHKetfesCKTIUL" -O edjx.zip
       - name: Extract edjx.zip to /usr/local/bin
         unarchive:
          src: edjx.zip
          dest: ./
       - name: copy edjx binary to /usr/local/bin
         copy:
           src: ./conf/edjx
           dest: /usr/local/bin
           mode: 0744 
       - name: init
         shell: edjx config init
       - name: edjx login
         shell:  edjx login -u suman+2@edjx.io -p Hello@123
       - name: permission to node register.sh
         command: chmod +x ./conf/node-register.sh
       - name: node register
         shell: |
          edjx genkeys --priv conf/runtime/certificates/private.pem --pub conf/runtime/certificates/public.pem
          edjx node init conf/runtime/certificates/private.pem
          edjx node gencsr conf/runtime/certificates/private.pem -o conf/runtime/certificates/csr.pem
          edjx node createcert conf/runtime/certificates/csr.pem -c conf/runtime/certificates/cert.pem
          edjx node gen-env conf/runtime/certificates/private.pem -o conf/runtime/.env_user
