---
# tasks file for edjruntime
       - name: github login
         shell: echo ceae4f110341a90997dbbe55dc0d7375c8aabf32 | docker login https://docker.pkg.github.com -u sriedjx --password-stdin
       - name: edjcli binary
         shell: wget "https://docs.google.com/uc?export=download&id=13pWZgKU9hbR1nhKv-laHKetfesCKTIUL" -O edjx.zip
       - name: Extract edjx.zip to /usr/local/bin
         unarchive:
          src: edjx.zip
          dest: ./
       - name: copy edjx binary to /usr/local/bin
         copy:
           src: ./conf/edjx
           dest: /usr/local/bin
           mode: 0744 
       - name: init
         shell: edjx config init
       - name: edjx login
         shell:  edjx login -u suman+2@edjx.io -p Hello@123
       - name: permission to node register.sh
         command: chmod +x ./conf/node-register.sh
       - name: node register
         shell: |
          spawn ./conf/node-register.sh
          expect "Save node private key to:"
          send -- "conf/runtime/certificates/private.pem\n"
          expect "Save node public key to:"
          send -- "conf/runtime/certificates/public.pem\n"
          expect "Save node certificate to:"
          send -- "conf/runtime/certificates/cert.pem\n"
          expect "Save node configuration to:"
          send -- "conf/runtime/.env_user\n"
          expect "IP Address for the node to listen on:"
          send -- "echo $(wget -q -O - ipinfo.io/ip)\n"
          exit 0
         args:
          executable: /usr/bin/expect
