version: "3.7"
services:
  runtime:
    image: docker.pkg.github.com/edjx/edjruntime/edjruntime:alpha
    env_file:
      - .env
      - .env_user
    restart: always
    stop_grace_period: 30s
    ports:
      - 80:80
      - 443:443
      - 5401:5401
      - 9001:9001
    volumes:
      - ./config:/runtime/config
      - ./certificates:/runtime/certificates
      - ./storage:/runtime/storage
