api:
  prefix: "/"
  addr: :8080
  timeout:
    upload: 30s
    fetch: 30s
log:
  level: debug
  export: none
fs:
  contentpath: /runtime/shared
  templocation: /runtime/temp/content
eventbus:
  url: "nats://localhost:4222"
cache:
  addr: localhost:6379
  ttl: 1s
isrelay: true
devmode: true