log_level: "debug"
topic_prefix: "org.relay.*"
topics:
  - org.relay.downloadstats:
     apiurl: "https://api.validate.edjx.network/api/downloads"
     method: "POST"
     retry: 2
  - org.relay.fnresult:
     apiurl: "https://api.validate.edjx.network/api/requests"
     method: "POST"
     retry: 2
register_with_edjx: true
edjx_register_freq: "5m"
edjx_api_url: "https://api.validate.edjx.network"
auth_cert_file: "certificates/cert.pem"
auth_priv_key_file: "certificates/private.pem"
event_bus_url: "nats://localhost:4222"
